[llm]
_type = "chatOpenai"
model_name = "gpt-3.5-turbo"
api_key = ""
temperature = 0.2
request_timeout=60


[db]
uri = "msyql://root:pwd123@localhost:3306/testdb"

[st.page]
title = "chartGPT"
icon = "ğŸ“Š"
layout = "wide"
input_placeholder = "é”€å”®æ¦‚è§ˆ\nä¸Šä¸ªæœˆæ±Ÿæµ™æ²ªæœ‰å¤šå°‘è®¢å•?\nä»¥æŠ¥è¡¨çš„æ–¹å¼æä¾›ä¸Šæœˆäº§å“çš„é”€é‡æ’è¡Œæ¦œ"
help_text = "ä½ å¯ä»¥é€šè¿‡æ–‡å­—å‘æˆ‘æå‡ºæ‚¨çš„ä¸€äº›åˆ†æéœ€æ±‚ã€‚\næ¯”å¦‚: \n- ä»¥æŠ¥è¡¨çš„æ–¹å¼æä¾›ä¸Šæœˆäº§å“çš„é”€é‡æ’è¡Œæ¦œ\n- é”€å”®æ¦‚è§ˆ\n- ä¸Šä¸ªæœˆæ±Ÿæµ™æ²ªæœ‰å¤šå°‘è®¢å•?"
